/*
 *  Nimble, an extensive application base for Grails
 *  Copyright (C) 2009 Intient Pty Ltd
 *
 *  Open Source Use - GNU Affero General Public License, version 3
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Commercial/Private Use
 *
 *  You may purchase a commercial version of this software which
 *  frees you from all restrictions of the AGPL by visiting
 *  http://intient.com/products/nimble/licenses
 *
 *  If you have purchased a commercial version of this software it is licensed
 *  to you under the terms of your agreement made with Intient Pty Ltd.
 */

nimble {
  organization {
    name = ""
    displayname = ""
    description = ""
    logo = ""
    logosmall = ""
    url = ""
  }

  facebook {
    federationprovider {
      enabled = false
      autoprovision = false
    }

    apikey = ""
    secretkey = ""
  }

  openid {
    federationprovider {
      enabled = false
      autoprovision = false
    }
  }

  recaptcha {
    // These keys are generated by the ReCaptcha service
	publickey = ""
	privatekey = ""

	// Include the noscript tags in the generated captcha
	noscript = true
  }

  messaging {
    registration {
      subject = "Your new account is ready!"
    }
    passwordreset {
      subject = "Your password has been reset"
    }

    mail {
      from = "App <app@company.com>"
      host = ""
      port = 25
      username = ""
      password = ""
      props = ["mail.smtp.auth": "false",
              "mail.smtp.socketFactory.port": "25",
              "mail.smtp.socketFactory.class": "javax.net.ssl.SSLSocketFactory",
              "mail.smtp.socketFactory.fallback": "false"]
    }
  }
}

environments {
  development {
    recaptcha {
      enabled = true
      secureapi = true
    }
  }
  production {
    recaptcha {
      enabled = true
      secureapi = true
    }
  }
}